In [1]:
import numpy as np

A = np.arange(1, 21).reshape(4, 5)

print("A =\n", A)
print("dtype:", A.dtype)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)

B = A.reshape(5, 4)
print("B =\n", B)

A =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
dtype: int64
ndim: 2
shape: (4, 5)
size: 20
itemsize: 8
B =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
a = np.array([[0., 0., 0.],
              [10., 10., 10.],
              [20., 20., 20.],
              [30., 30., 30.]])

b = np.array([0., 1., 2.])

c = a + b
print("c =\n", c)

mask = (c >= 22)
print("mask =\n", mask)

count = np.sum(mask)
print("count =", count)

c =
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]
mask =
 [[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]
count = 4


In [3]:
grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])

print("sum =", np.sum(grades))
print("min =", np.min(grades))
print("max =", np.max(grades))
print("mean =", np.mean(grades))
print("std =", np.std(grades))
print("var =", np.var(grades))

print("mean per column =", np.mean(grades, axis=0))
print("mean per row =", np.mean(grades, axis=1))
print("max per row =", np.max(grades, axis=1))

sum = 1054
min = 70
max = 100
mean = 87.83333333333333
std = 8.792357792739987
var = 77.30555555555556
mean per column = [95.25 85.25 83.  ]
mean per row = [84.33333333 92.33333333 87.         87.66666667]
max per row = [ 96 100  94 100]


In [4]:
arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])

print("sum of each row =", np.sum(arr, axis=1))
print("sum of each column =", np.sum(arr, axis=0))
print("overall mean =", np.mean(arr))

sum of each row = [12  9 27]
sum of each column = [10 16 22]
overall mean = 5.333333333333333


In [5]:
import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

# Add B to A
add_result = A + B
print("A + B =\n", add_result)

# Multiply A by 2
mul_result = A * 2
print("A * 2 =\n", mul_result)

# Subtract 5 from A
sub_result = A - 5
print("A - 5 =\n", sub_result)

A + B =
 [[11 22 33]
 [41 52 63]]
A * 2 =
 [[ 20  40  60]
 [ 80 100 120]]
A - 5 =
 [[ 5 15 25]
 [35 45 55]]


In [6]:
grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

# Index of largest value in whole array
max_index = np.argmax(grades)
print("Index of largest value (flattened):", max_index)

# Index of highest grade in each row
row_max_index = np.argmax(grades, axis=1)
print("Index of max in each row:", row_max_index)

# Index of lowest grade in each column
col_min_index = np.argmin(grades, axis=0)
print("Index of min in each column:", col_min_index)

Index of largest value (flattened): 5
Index of max in each row: [2 2 1]
Index of min in each column: [2 1 2]


In [ ]:
part2

In [7]:
import numpy as np

# إنشاء المصفوفة
table = np.array([
    [5, 8, 2, 7],
    [1, 9, 4, 3],
    [6, 0, 11, 10],
    [12, 13, 14, 15]
])

print("Table =\n", table)

# الصف الثاني (R2)
print("Second row =", table[1])

# العمود الثالث (C3)
print("Third column =", table[:, 2])

# sub-table (R2–R3 و C2–C3)
print("Sub-table =\n", table[1:3, 1:3])

Table =
 [[ 5  8  2  7]
 [ 1  9  4  3]
 [ 6  0 11 10]
 [12 13 14 15]]
Second row = [1 9 4 3]
Third column = [ 2  4 11 14]
Sub-table =
 [[ 9  4]
 [ 0 11]]


In [9]:
scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 65, 72]
])

print("Original scores =\n", scores)

# زيادة درجات الفيزياء +5 (العمود الثاني)
scores[:, 1] = scores[:, 1] + 5

# استبدال درجات أول طالب
scores[0] = [100, 100, 100]

# جعل عمود CS (الأخير) = 0
scores[:, 2] = 0

print("Updated scores =\n", scores)

Original scores =
 [[70 80 90]
 [60 75 85]
 [88 92 79]
 [55 65 72]]
Updated scores =
 [[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [10]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 4])

In [11]:
A * B

array([[ 5, 12],
       [21, 32]])

In [12]:
A * v

array([[ 2,  8],
       [ 6, 16]])

In [13]:
np.random.seed(0)

matrix = np.random.randint(-5, 6, (4, 4))
print(matrix)

[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]


In [14]:
np.unique(matrix, axis=0)

array([[-3, -1,  2,  1],
       [ 0, -5, -2, -2],
       [ 2,  4, -2,  0],
       [ 3,  3,  5, -4]], dtype=int32)

In [15]:
import numpy as np

x = np.array([2, 0, 1, 5, 4, 1, 9])
A = np.array([[3, 8, 1],
              [6, 2, 9]])

# Part 1: argsort
indices = np.argsort(x)
sorted_x = x[indices]

print(indices)
print(sorted_x)

# Part 2: min location
min_index = np.unravel_index(A.argmin(), A.shape)
print(min_index)

# Part 3: where
indices_where = np.where(x > 3)
print(indices_where)

# Part 4: split
parts = np.split(x, [2, 5])
for part in parts:
    print(part)

# Part 5: expand and squeeze
expanded = np.expand_dims(x, axis=0)
print(expanded)

squeezed = np.squeeze(expanded)
print(squeezed)

[1 2 5 0 4 3 6]
[0 1 1 2 4 5 9]
(np.int64(0), np.int64(2))
(array([3, 4, 6]),)
[2 0]
[1 5 4]
[1 9]
[[2 0 1 5 4 1 9]]
[2 0 1 5 4 1 9]


In [16]:
# Argsort
x = np.array([4, 2, 7, 1, 5])

sorted_indices = np.argsort(x)
print(sorted_indices)
print(x[sorted_indices])

# شرح:
# np.argsort(x) لا يرجع القيم مرتبة مباشرة،
# بل يرجع فهارس العناصر بعد الترتيب.
# باستخدام هذه الفهارس نستطيع عرض المصفوفة بشكل مرتب.


# Minimum Location
A = np.array([[8, 3, 6],
              [1, 9, 4]])

min_index = A.argmin()
location = np.unravel_index(min_index, A.shape)

print(min_index)
print(location)

# شرح:
# A.argmin() يبحث عن أصغر قيمة في المصفوفة
# ويرجع موقعها كرقم واحد.
# np.unravel_index يحول هذا الرقم إلى صف وعمود.


# Where
x = np.array([1, 4, 2, 6, 3, 7])

result = np.where(x > 3)
print(result)

# شرح:
# np.where(x > 3) يبحث عن العناصر
# التي تحقق الشرط (أكبر من 3)
# ثم يعرض أماكنها داخل المصفوفة.


# Split
x = np.array([10, 20, 30, 40, 50, 60, 70])

parts = np.split(x, [2, 5])

print(parts)

# شرح:
# np.split يقسم المصفوفة إلى أجزاء
# حسب المواقع المحددة.
# هنا تم تقسيمها إلى:
# أول عنصرين، ثم 3 عناصر، ثم الباقي.


# Expand & Squeeze
x = np.array([1, 2, 3, 4, 5, 6, 7])

expanded = np.expand_dims(x, axis=0)
print(expanded.shape)

squeezed = np.squeeze(expanded)
print(squeezed.shape)

# شرح:
# np.expand_dims يضيف بُعد جديد للمصفوفة
# مثل تحويلها من صف عادي إلى صف داخل مصفوفة.
# np.squeeze يحذف الأبعاد الزائدة
# ويرجعها إلى شكلها الطبيعي.

[3 1 0 4 2]
[1 2 4 5 7]
3
(np.int64(1), np.int64(0))
(array([1, 3, 5]),)
[array([10, 20]), array([30, 40, 50]), array([60, 70])]
(1, 7)
(7,)
